apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "39"
spec:
  encryptedData:
    config: AgCBNSCU7tEVzdKDGsfU2ywZ1UGQIyN4+C+B7c03FGsWhGo4sRCn1O0B8hFO7LkBs4hKW5mOYW+H4jegDfnjuWOJxZHHJlTayY6qlLR6Cbu0ARkCj82Cf0sbMLjCFD5/ccD5XDD5Ijvx/d3zlarEY/Ebg/Yg5iQQamFuoEICuIN9YnuX3JbpaaJvv6tVMDOBoyxvF5hvExr7hrNLHp+flgUrI+Z5fKVHNk2BRYF9FsvSZLJ8IU1wowmJhceI3OG+1zn5jVWJP0kEyq+DsOSzG9nrmFjLaR4gXIsWwXDm4IEkhVP80Md+EjlspYfoxgboSOFMKYTSlNPFwG7AesiK9+csnWRJFIYfUYYHQa6mAtwpdtjCBo5meoU08zgWuQKfbdpsY/j3iekC5afyuqjtPn+bKCqXfOpIiLkJCqRccb2fNcNYmsQWKKkp31H6GFBA1VZQVETVAt3ALE3JuuMm9nxKDqr4hXBuOAySviA1q/jVXaxBsvxlEsTvlqtAbUdAAxG1TYNSshCYFq4dEhkSuQzkNYL2V8/A2MLeq0yfMnyoUJfSYwUCIhwbGtEf7V9El8IbO+e2Ouveok5ILAdtDYXpr9igZNd6rShd47q+1bsKrTKIfbMHICgBscapWsUX2pGVUwJjejK6IiAIcCWU/0Q+umK+GytjPX0XkUQ7LVTAHD0wjK/bHD4JHF1lK4Sz+j22F1b2Lhv2nP3KvOLwgrZQT0+BoFJp82kNu2hgTg+L3hdTyB0Tg3OrTIAQfjfG6+X9evXO1KouQjgu6FNl6w7p402wFmHb9hCmCdv65ODOWffJP4F/VIVqqzbH1brmJSZBtX9dKOqsXzsTNq/cbSNz5fr7+cAVocEb5ah/Hf9AnZXBX8XCHFDrid6OONmRPjMRV8l0JygM/98+ANpoxbSO9XB41XHclq+xc6IFE3hlap/9tbRKuDdOqGEo/fAV2ODzErKciv+3TvSy4ms6B88B1SDx3m7fayiWzPx+BPVCm8Bsc469VYAu9hbd+A0xkvkBAQdFKIHjtyQfYd0q25vu
  template:
    metadata:
      name: gitlab-registry-storage
      namespace: gitlab
    type: Opaque