apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-valkey-credentials
  namespace: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "39"
spec:
  encryptedData:
    password: AgCPQoq7gRUuMsLV5SF0QFzq/o1PATA5va8vbN8RBZEYy+Rb/0Gn44wvk9O5yWamEkc2ihrEx5pKcSjswgg9mbCMgLIhGZdLEekvajgRg2EcJVLzslXiWQQF2/C1na6B1VI6tlDDBiJ2SEZpmpN1rs39yruTP4hy+0St0RdqUJPTQ3phX6JfNVWarI9ppWKpW5bEQTIkwajoFSOOlV/m1/ePH1lLrFUpXmZqOGb+xr/mzLKnuir6wYq9tlCz7xS6I6Za2RZmmokh7em2gtP4/N0aw5e/1z8IIq/JlUNcwVL7SeLQ8ofS64bhLej5/tJWipTcXNb7g3qeE0mvb2Exl9VdGDlO4bWFJ+qvtGrKA09VNEJ4TeTxuMnu/2k9ZEFXoqBczeQ+Lm50HcjpPc5v3sft7q0NAtOS2XCMADTa6ICFmJulocw+rNjmmNRbkiZb01OQZoAq7JmdtuY/cjkDcfoSH3Gn/dY59JH8dqcDaaFOyVcjiwx1zTv2aieNZjSpijsE0TfdfhRDNqjuiZVP28KEeFKQx819p6V4f8ljVgE2hVzjGnEoQYMsrxrH1wfCLl7V9YGaOjB7iIQcrRES/q6LHXPtaY7uFRKT7y+AHF1n9AfTN2ciZ+GmbFq2XoymyJ79yhTRxLC1UDtoKfx9sZzEBVA51uAt/u956FB+Wmp5EOru0ih3T+Sv/OaL3mHQF7Q8Ap3lVPiZTCyyBs2BdJb8PvWWmOG7bxKfB0M/F8kg61F92MGBmPxuoWJYAw==
  template:
    metadata:
      name: gitlab-valkey-credentials
      namespace: gitlab