apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: homelab
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1
        existingSecret: minio-credentials
        persistence:
          enabled: true
          storageClass: longhorn
          size: 20Gi
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
        service:
          type: ClusterIP
        consoleService:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: storage

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true