apiVersion: postgresql.cnpg.io/v1
kind: Database

metadata:
  name: gitlabhq-production
  namespace: databases

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  name: gitlabhq_production

  owner: gitlab

  cluster:
    name: postgres

  databaseReclaimPolicy: retain