apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-postgres
  namespace: gitlab
spec:
  encryptedData:
    password: AgBbsFshvEsY8z+0oqy0o8vJ24p/WUfHfrvdzQrDFU1q8NP37QWizQggOVjudgbJZK6lghiGfx88R506sF7zD76A5q2ZJk7sMmQlGyOWr0l1jLjCqMYplVbBbxbSoeTNmjV4vfN7bWdWB+vYv4xHjpuGSG7AYFgin+zkhb07MTLSnu7OaovGhE29B/nmylBTABzFaBG3w90VjebL0JFbK5YDyFn6jBGopROa8X1NOS30NH3RdLziLE/+aPbjH+TEISIv9BRLHj1IvuzRwEZa/lfpHuhKvhxLZpayEVdphTmdjKf6KzAjmC+0uJnAtDGRnJQWlOOp1fjMdU5GFxKAi2nghwYElYChgj9n4b3P3Gl/YhIhH/e18NsojWQ0mEAFR+z/E4/Dl6n4Ed7WPrtDCSvx4218+V8TJ6durWx6Mo1JwgzGt4Js7JBAwNho9q+cb9qbSjTw2VnsZ1eW9M/dMzZyeqXO2HiU4rg7HFE2xL54MF0WYMIsOBARiYjK/7SEulL1bRRz6u2+glxMPgtkzuBrTpsOSlu2dlLPEQlR2bWNZJU6X8e+3Fgz0D1JzNsjmp3Xr1BDZo/Kjo6jBGi8qvoyCF45WgFm5iW604B84uDOXdEoeotU5h8nTvDKm4AT6hyQdvW7V3NsVdd+ubVGiRlHgh1Wq7Dd4LO8Zk18hIQYtTuPuEaSWacGG74JbDUci4AGMztfokbbMi7YSNuvDZ4tCbSLfr8SnXViEaQVAA1QzEDj3Ucduaueb5GTSA==
    username: AgAzeiPcqoyXSA2q0d65vpXanl0koQdAY28CTHj+LcjXxz6T1SXPbl3/9XMcjcLeznTgF3F+t4qhhB/t32wE8pjjyyGxJliUCksFcQcEaqT/ISk+TAiaRjIXo+bge6yLhA69ow18xubqX4sK5npg2K93aVrV0j2iqL5Xp9OuNL+CMRriX8lpuuWqgv2+j6bs80ck6NTGLVrD3x80oTF+jhXpRPm0evCx/Kh8fRWWtXosRgcYlQ6zCkX+wZ9EDL5NxktI8yRC7ABQh52tWi194bc/vtD0khotBVuvaCoFdoaU5xyCAjMGTdmq4zYnF/aXdtjHf4ZdV70PBeXJPN/aVSxme5ByK8cx90Y5w5lU2as35H5CWZ7EmFZCs2tQP3agJoRJHeETSDrFT/96Av+3fg1keB8uHvDHSOl9XO64U/HHKENsKorLAh/kab6f/0eZXzFdvPdk1TnsFGGPNlHSZYiEIb8dBG2KWi+DeJw3UrybjOjxTScCYDIPQrdWZEFHv/kdTzF3JuKHOOSNMHxxFNv+61OIJkOhLKVt3qggtWSX1KVe6uTlLvMIWO/DIaoxUy3Vc7LNye47F8IzAO1T454A0a+8For4VcSUxzgWp9CpQuegPCmDQFMKKnSK1NP6ggBPw05WBpjv3EY/2lkq7MUNEfRYpFBoQmQCPQ425HqpsmSv7NVwb2PP3oAIWrUJmGBOYbYIcfE=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: gitlab-postgres
      namespace: gitlab
    type: kubernetes.io/basic-auth