apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgres
  namespace: databases

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:18.3

  storage:
    storageClass: longhorn
    size: 10Gi

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-app