apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-app
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    password: AgAk/HxOEQTP1WVv00ge7olurmoYwIn1galRPWjKEqSVXP4xA6oX7YgYm6bAKDeyd6gPRk2IIz6RKX09hzM2xyDcOW+rVU6sdYJoZomg53tsQI+RSTvEKmVxNwql9xEsN3nwsFCPnYxFPSzoB/SWmpWGkLG/z/tBkitdekWvPY9nJ7VRxZuTmVJUbmdVAR3DHF+vmxyVlBFT+FrvZvlLSxZzvjSqk87QA6IuKSBt69mTNH8Y3/ixPODgbt5L8ocWsbT+ut05ZuEx6toDktU7ltztI/F/dP0mrjDXvoFJiU9vMk8mJxAHvS7jVowMJOa4eFnrXf3Ciz9REV+TvsCvKzLyFjdi5zxUuUUrNYUo50YP679SgDcIE6vqNCigh75+JjgJGa9krYDkjp30n5MKs25aT9RrNfsjQwOGEO5qJY2QSeZYMarV0oUcXzWppKh5ZZBb+cBbLklBKy3eYS3LgfJY8BQxg3E2LkTckDHQQxInp4EgxHDDRhExlIHG6JyRYL1asAiVgQfokHEZlCuJ06xTLLi7rpHehXB8G+hgN1QkGSXgunu/rJUOswGCN8WYbMQ4vMmGXeFxvzjMn41wn49L8B7E0x7xuOOsCtv8AuXr0tetYdbTVbRzMyganTJhW9oT3A0LxjCkN/48sR62U9LxTAsRJ9rmd6rpPfnPXcmC2oY+6s1WkLBUyQlUhwykkgvBCtr1jbe13vHD9/bUerNgKzCWAfjhx+IufBpadXx03ilk3i4qIU0Wby6/aQ==
    username: AgAIKD0FWvI1gE2eg1FQqzRIq6H2uis98YmT6h4CMAWQ9kdF5XVcukI1IFKYAmaZxNUvfeD1+vRl91AWJzhtuXHdX6qx1DhgYYbN0aXi/u6AqewCVhNn2u4AcYGXQTgOD1G6/RkYu4Rk1a0pqGAwgu0rcEhdo1Jt5olyQZMH4x48ukqwl8ZtTpXeEzr6S1/19zaQXLtBlsIJiNpVIgnsmtJBUsIAbkQ/5WZIrZ51OJpRt9xfITzDHGPSDJNImzixAZnxhycYpT8gHhwXwLOSZiCI9jK2/CVeTf3H0sOMjlF5D9xbS5c3lpaz3PpziYXgVngOHhmWMDGufefq9eo27Z33gN8qmZ71a7I7RdLRBMIWIwhdJY4EfYuqiOGm4hBKPly+C6rDULf2izaggc33jEE1VcfLr9iixlUwDucHzSmBeYWCfHev5DZqc2W3/egE+shCj/NdHTegfKsWalMTyv3rBFrLbw9dMDoTuHsohbWSJU/7pV7FhSj+m2VE8ixDPJfNfsIi8eprIo/UKHgZF7dy+VY+OOxzsgH6xb8Tk9LyM1tOWfcungDzCp/BGbnMfajkWJ0pfYNuuBBxsGplASdyPEXc6lTPkKvHU5oXi5h9mOanHb9Ih/hH0dkFSsOd6U/89CeOjqJdwxj6AHieulZiH/dtyFrS8MJIGdZPF3NK3X+H4XA5Z+NpS/dv/qK0uRjK+yQ=

  template:
    metadata:
      name: postgres-app
      namespace: databases
    type: kubernetes.io/basic-auth