apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "22"

spec:
  project: homelab

  source:
    repoURL: ssh://git@github.com/harishSudalaimani/gitlab.git
    targetRevision: main
    path: manifests/databases/postgres

  destination:
    server: https://kubernetes.default.svc
    namespace: databases

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true